# Generated by Django 5.0.1 on 2024-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0002_alter_player_email_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('location', models.CharField(max_length=30, verbose_name='location')),
                ('number_of_players', models.IntegerField(verbose_name='number of players')),
                ('type', models.CharField(max_length=30, verbose_name='type')),
            ],
        ),
    ]
