# Generated by Django 5.0.1 on 2024-01-20 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0007_alter_fixture_opponent_goals_1st_leg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
        migrations.AlterField(
            model_name='fixture',
            name='opponent_goals_1st_leg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='opponent goals 1st leg'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='player_goals_1st_leg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='player goals 1st leg'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='stage',
            field=models.CharField(choices=[('G', 'Group'), ('QF', 'Quarter-final'), ('SF', 'Semi-final'), ('3P', '3rd place'), ('F', 'Final')], max_length=2, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='draws',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='draws'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='goals_against',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='goals against'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='goals_difference',
            field=models.IntegerField(default=0, verbose_name='goals difference'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='goals_for',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='goals for'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='group_name',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], max_length=1, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='loses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='loses'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='matches_played',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='matches played'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='wins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='wins'),
        ),
    ]
