# Generated by Django 5.0.1 on 2024-01-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0013_fixture_status_alter_fixture_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstage',
            name='position',
        ),
    ]
