# Generated by Django 5.0.1 on 2024-02-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0016_remove_knockoutstage_opponent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
