name: Auto Commit Changes

on:
  push:
    branches:
      - main
  # Auto-commit every 30 minutes
  schedule:
    - cron: '*/30 * * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Auto-save: $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi 